name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - uses: extractions/setup-just@v1

      - name: Build
        run: just

      - name: Test
        run: just test

