name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cedrickring/golang-action@1.7.0
        with:
          args: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cedrickring/golang-action@1.7.0
        with:
          args: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cedrickring/golang-action@1.7.0
        with:
          args: make build
