name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2

      - name: Dowload Dependencies
        run: go mod vendor -v

      - name: Build
        run: go build -o bin/toshokan main.go

      - name: Test
        run: go test ./... -v --cover
