name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Go Lint
        run: sudo apt-get install golint

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test

