name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: icepuma/rust-action@master

      - name: Build
        run: cargo build

      - name: Clippy
        run: cargo clippy -- -Dwarnings

      - name: Test
        run: cargo test
